[tool.ruff]
line-length = 100
target-version = "py312"
extend-exclude = ["migrations"]

[tool.ruff.lint]
select = ["E", "F", "I"]
# Ignore star-import/unused-name ONLY in settings modules.
per-file-ignores = { "config/settings/*.py" = ["F401", "F403"] }
