# Generated by Django 5.2.6 on 2025-09-21 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Short prompt shown to participants.", max_length=200
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        blank=True, help_text="Longer guidance or context."
                    ),
                ),
                (
                    "qtype",
                    models.CharField(
                        choices=[
                            ("Multiple Choice", "Multiple Choice"),
                            ("Open Ended", "Open Ended"),
                            ("Scale", "Scale (1-5)"),
                        ],
                        default="Open Ended",
                        max_length=16,
                    ),
                ),
                ("tags", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Interview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Session title"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Guidance shown to participants"
                    ),
                ),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "is_published",
                    models.BooleanField(
                        default=False, help_text="Visible to participants if enabled."
                    ),
                ),
                (
                    "confidentiality",
                    models.CharField(
                        choices=[
                            ("public", "Public results"),
                            ("internal", "Internal only"),
                            ("anonymous", "Anonymous outputs"),
                        ],
                        default="internal",
                        help_text="How outputs are shared.",
                        max_length=16,
                    ),
                ),
                (
                    "project_code",
                    models.CharField(
                        blank=True,
                        help_text="Engagement or project code.",
                        max_length=64,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "allowed_participants",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Empty = any authenticated user.",
                        related_name="invited_interviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_interviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "questions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="interviews",
                        to="interviewhub.question",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer_text", models.TextField(blank=True)),
                (
                    "metric_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Sentiment/LLM score",
                        max_digits=5,
                        null=True,
                    ),
                ),
                ("is_anonymous", models.BooleanField(default=False)),
                ("consent_given", models.BooleanField(default=False)),
                (
                    "meta",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Freeform context (dept, office, role)",
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Participant",
                    ),
                ),
                (
                    "interview",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="interviewhub.interview",
                        verbose_name="Session",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="interviewhub.question",
                    ),
                ),
            ],
            options={
                "ordering": ["-submitted_at"],
                "unique_together": {("candidate", "interview", "question")},
            },
        ),
    ]
