# Generated by Django 5.2.6 on 2025-09-21 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interviewhub", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="options",
            field=models.JSONField(
                blank=True, default=list, help_text="For MCQ: ['A', 'B', ...]"
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="scale_max",
            field=models.IntegerField(
                blank=True, help_text="For SCALE: upper bound (default 5)", null=True
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="scale_min",
            field=models.IntegerField(
                blank=True, help_text="For SCALE: lower bound (default 1)", null=True
            ),
        ),
    ]
