# Generated by Django 5.2.6 on 2025-09-23 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interviewhub", "0002_question_options_question_scale_max_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="scale_max",
        ),
        migrations.RemoveField(
            model_name="question",
            name="scale_min",
        ),
        migrations.AlterField(
            model_name="question",
            name="options",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="For Multiple Choice: ['A', 'B', ...]",
            ),
        ),
    ]
